// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import javax.swing.JOptionPane;

/************************************************************/
/**
 * 
 */
public abstract class Catalogo {
     	protected Libros libros; 
    protected Memorias memorias;
    protected Revistas revistas;
    protected Tesis tesis;
    protected Periodicos periodicos;
    
    public Catalogo(String titulo, String fechaIngreso,String Autor) {
    	this. titulo =  titulo;
        this.fechaIngreso = fechaIngreso;
        this.Autor=Autor;
      
        
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getFechaIngreso() {
        return fechaIngreso;
    }

    public void setFechaIngreso(String fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public String getAutor() {
        return Autor;
    }

    public void setAutor(String Autor) {
        this.Autor = Autor;
    }
	/**
	 * 
	 */
	private String titulo;
	/**
	 * 
	 */
	private String fechaIngreso;
	/**
	 * 
	 */
	private String Autor;
        
        public PrintStream getPrintStream(String nombreArchivo) {
        File archivo = new File(nombreArchivo);
        PrintStream ps = null;
        try {
            FileOutputStream fos = new FileOutputStream(archivo, true);
            ps = new PrintStream(fos);

        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(null, "error");
            
        }
        return ps;
    }
};
